const Router = require ('express')
const router = new Router()
const userRouter = require ('./userRouter')
const hackathonRouter = require ('./hackathonRouter')
const classesRouter = require ('./classesRouter')
const materialRouter = require ('./materialRouter')
const groupRouter = require ('./groupRouter')
const forumRouter = require ('./forumRouter')
const forumSectionRouter = require ('./forumSectionRouter')
const journalRouter = require ('./journalRouter')
const scheduleRouter = require ('./scheduleRouter')
const resultRouter = require ('./resultRouter')
const emulatorRouter = require ('./emulatorRouter')
const emulatorConfRouter = require ('./emulatorConfRouter')
const emulatorLogRouter = require ('./emulatorLogRouter')

router.use('/user', userRouter)
router.use('/hackathon', hackathonRouter)
router.use('/classes', classesRouter)
router.use('/material', materialRouter)
router.use('/group', groupRouter)
router.use('/forum', forumRouter)
router.use('/forumSection', forumSectionRouter)
router.use('/journal', journalRouter)
router.use('/schedule', scheduleRouter)
router.use('/result', resultRouter)
router.use('/emulator', emulatorRouter)
router.use('/emulatorConf', emulatorConfRouter)
router.use('/emulatorLog', emulatorLogRouter)

module.exports = router