const Router = require ('express')
const router = new Router()
const userRouter = require ('./userRouter')
const classRouter = require ('./classRouter')
const lessonRouter = require ('./lessonRouter')
const materialRouter = require ('./materialRouter')
const careerRouter = require ('./careerRouter')
const forumRouter = require ('./forumRouter')
const forumSectionRouter = require ('./forumSectionRouter')
const journalRouter = require ('./journalRouter')
const scheduleRouter = require ('./scheduleRouter')
const olympiadRouter = require ('./olympiadRouter')
const resultRouter = require ('./resultRouter')
const electiveRouter = require ('./electiveRouter')

router.use('/user', userRouter)
router.use('/class', classRouter)
router.use('/lesson', lessonRouter)
router.use('/material', materialRouter)
router.use('/career', careerRouter)
router.use('/forum', forumRouter)
router.use('/forumSection', forumSectionRouter)
router.use('/journal', journalRouter)
router.use('/schedule', scheduleRouter)
router.use('/olympiad', olympiadRouter)
router.use('/result', resultRouter)
router.use('/elective', electiveRouter)

module.exports = router