const Router = require ('express')
const router = new Router()
const userRouter = require ('./userRouter')
const forumRouter = require ('./forumRouter')
const materialRouter = require ('./materialRouter')

const hackathonElectricRouter = require ('./RoutesForElectric/hackathonElectricRouter')
const classesElectricRouter = require ('./RoutesForElectric/classesElectricRouter')
const groupElectricRouter = require ('./RoutesForElectric/groupElectricRouter')
const forumSectionElectricRouter = require ('./RoutesForElectric/forumSectionElectricRouter')
const journalElectricRouter = require ('./RoutesForElectric/journalElectricRouter')
const scheduleElectricRouter = require ('./RoutesForElectric/scheduleElectricRouter')
const resultElectricRouter = require ('./RoutesForElectric/resultElectricRouter')
const emulatorElectricRouter = require ('./RoutesForElectric/emulatorElectricRouter')
const emulatorConfElectricRouter = require ('./RoutesForElectric/emulatorConfElectricRouter')
const emulatorLogElectricRouter = require ('./RoutesForElectric/emulatorLogElectricRouter')

const classSchollRouter = require ('./RoutesForScholl/classSchollRouter')
const lessonSchollRouter = require ('./RoutesForScholl/lessonSchollRouter')
const careerSchollRouter = require ('./RoutesForScholl/careerSchollRouter')
const forumSectionSchollRouter = require ('./RoutesForScholl/forumSectionSchollRouter')
const journalSchollRouter = require ('./RoutesForScholl/journalSchollRouter')
const scheduleSchollRouter = require ('./RoutesForScholl/scheduleSchollRouter')
const olympiadSchollRouter = require ('./RoutesForScholl/olympiadSchollRouter')
const resultSchollRouter = require ('./RoutesForScholl/resultSchollRouter')
const electiveSchollRouter = require ('./RoutesForScholl/electiveSchollRouter')

router.use('/user', userRouter)
router.use('/material', materialRouter)
router.use('/forum', forumRouter)

router.use('/hackathonElectric', hackathonElectricRouter)
router.use('/classesElectric', classesElectricRouter)
router.use('/groupElectric', groupElectricRouter)
router.use('/forumSectionElectric', forumSectionElectricRouter)
router.use('/journalElectric', journalElectricRouter)
router.use('/scheduleElectric', scheduleElectricRouter)
router.use('/resultElectric', resultElectricRouter)
router.use('/emulatorElectric', emulatorElectricRouter)
router.use('/emulatorConfElectric', emulatorConfElectricRouter)
router.use('/emulatorLogElectric', emulatorLogElectricRouter)

router.use('/classScholl', classSchollRouter)
router.use('/lessonScholl', lessonSchollRouter)
router.use('/careerScholl', careerSchollRouter)
router.use('/forumSectionScholl', forumSectionSchollRouter)
router.use('/journalScholl', journalSchollRouter)
router.use('/scheduleScholl', scheduleSchollRouter)
router.use('/olympiadScholl', olympiadSchollRouter)
router.use('/resultScholl', resultSchollRouter)
router.use('/electiveScholl', electiveSchollRouter)

module.exports = router